version: '3'

services:
  # build:
  #   image: maven:3-eclipse-temurin-17-alpine
  #   working_dir: /app
  #   command: >
  #     mvn clean package
  #   volumes:
  #     - .:/app
  tomcat:
    image: tomcat:8-jre8-alpine
    ports:
      # http://localhost:8888/cluster-diag/
      - 8888:8080
    volumes:
      - ./target/cluster-diag.war:/usr/local/tomcat/webapps/cluster-diag.war
    environment:
      - DUMMY=NOT_ME!
      - SECRET=INFORMATION

  wildfly:
    image: quay.io/wildfly/wildfly:27.0.1.Final-jdk17
    ports:
      # http://localhost:8889/cluster-diag/
      - 8889:8080
      - 8890:9990
    command: >
      sh -c "/opt/jboss/wildfly/bin/add-user.sh -u wildfly -p wildfly -r ManagementRealm
      && /opt/jboss/wildfly/bin/standalone.sh -b 0.0.0.0 -bmanagement 0.0.0.0"
    volumes:
      - ./target/cluster-diag.war:/opt/jboss/wildfly/standalone/deployments/cluster-diag.war
    environment:
      - DUMMY=DEFINITELY_NOT_ME!
      - SECRET=STUFF
